import Head from "next/head";
import { Manrope } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Gallery from "@/components/Gallery";
import MainLayout from "@/Layout/Mainlayout";

const manrope = Manrope({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${manrope.className}`}>
        <MainLayout>
          <h2>HomePage</h2>
          <p>lorem impsum</p>
        </MainLayout>
      </main>
    </>
  );
}
